export const assets = [
  {
    id: "AST-001",
    name: "Siemens S7-1500 PLC",
    type: "PLC",
    vendor: "Siemens",
    model: "S7-1516",
    firmware: "2.9.4",
    ip: "10.10.12.24",
    mac: "00:1A:2B:3C:4D:5E",
    location: "Plant A - Assembly Line 1",
    criticality: "critical",
    status: "active",
    lastScan: "2024-01-15T10:30:00Z",
    vulnerabilities: 3,
    protocols: ["Profinet", "S7comm"],
  },
  {
    id: "AST-002",
    name: "Allen-Bradley ControlLogix",
    type: "PLC",
    vendor: "Rockwell",
    model: "1756-L83E",
    firmware: "33.011",
    ip: "10.10.12.31",
    mac: "00:2C:3D:4E:5F:6A",
    location: "Plant A - Packaging",
    criticality: "critical",
    status: "warning",
    lastScan: "2024-01-15T09:45:00Z",
    vulnerabilities: 5,
    protocols: ["EtherNet/IP", "CIP"],
  },
  {
    id: "AST-003",
    name: "Schneider Modicon M340",
    type: "PLC",
    vendor: "Schneider",
    model: "BMXP342020",
    firmware: "3.40",
    ip: "10.10.15.12",
    mac: "00:3E:4F:5A:6B:7C",
    location: "Plant B - HVAC Control",
    criticality: "high",
    status: "active",
    lastScan: "2024-01-15T11:00:00Z",
    vulnerabilities: 2,
    protocols: ["Modbus TCP", "EtherNet/IP"],
  },
  {
    id: "AST-004",
    name: "Siemens HMI Comfort Panel",
    type: "HMI",
    vendor: "Siemens",
    model: "KTP1200",
    firmware: "17.0.1",
    ip: "10.10.12.50",
    mac: "00:4A:5B:6C:7D:8E",
    location: "Plant A - Control Room",
    criticality: "high",
    status: "active",
    lastScan: "2024-01-15T08:15:00Z",
    vulnerabilities: 4,
    protocols: ["Profinet", "HTTP"],
  },
  {
    id: "AST-005",
    name: "GE iFIX SCADA Server",
    type: "SCADA",
    vendor: "GE",
    model: "iFIX 6.5",
    firmware: "6.5.2",
    ip: "10.10.10.5",
    mac: "00:5B:6C:7D:8E:9F",
    location: "Central Control Room",
    criticality: "critical",
    status: "active",
    lastScan: "2024-01-15T07:30:00Z",
    vulnerabilities: 6,
    protocols: ["OPC-UA", "DCOM"],
  },
  {
    id: "AST-006",
    name: "Cisco IE4000 Switch",
    type: "Network",
    vendor: "Cisco",
    model: "IE-4000-8GT4G-E",
    firmware: "15.2(8)E",
    ip: "10.10.10.1",
    mac: "00:6C:7D:8E:9F:A0",
    location: "Plant A - Network Closet",
    criticality: "high",
    status: "active",
    lastScan: "2024-01-15T06:00:00Z",
    vulnerabilities: 1,
    protocols: ["SNMP", "SSH"],
  },
  {
    id: "AST-007",
    name: "ABB ACS880 VFD",
    type: "Drive",
    vendor: "ABB",
    model: "ACS880-01",
    firmware: "2.72",
    ip: "10.10.14.88",
    mac: "00:7D:8E:9F:A0:B1",
    location: "Plant A - Motor Control",
    criticality: "medium",
    status: "offline",
    lastScan: "2024-01-14T22:00:00Z",
    vulnerabilities: 0,
    protocols: ["Modbus TCP"],
  },
  {
    id: "AST-008",
    name: "Endress+Hauser Flowmeter",
    type: "Sensor",
    vendor: "Endress+Hauser",
    model: "Promag 400",
    firmware: "1.04.00",
    ip: "10.10.16.22",
    mac: "00:8E:9F:A0:B1:C2",
    location: "Plant B - Process Line",
    criticality: "low",
    status: "active",
    lastScan: "2024-01-15T10:00:00Z",
    vulnerabilities: 0,
    protocols: ["HART", "Modbus RTU"],
  },
]

export const vulnerabilities = [
  {
    id: "VLN-001",
    cve: "CVE-2024-1001",
    title: "Unauthenticated access on PLCs",
    description: "Default admin credentials discovered on multiple HMI devices enabling unauthorized access.",
    severity: "critical",
    cvss: 9.8,
    affectedAssets: ["AST-001", "AST-002", "AST-004"],
    vendor: "Siemens",
    advisorySource: "Siemens ProductCERT",
    published: "2024-01-10T00:00:00Z",
    status: "open",
    exploitAvailable: true,
    patchAvailable: true,
    remediation: "Disable default account and enforce MFA",
  },
  {
    id: "VLN-002",
    cve: "CVE-2024-0892",
    title: "Outdated HMI firmware",
    description: "Outdated firmware version with known buffer overflow vulnerability.",
    severity: "high",
    cvss: 8.1,
    affectedAssets: ["AST-004", "AST-003"],
    vendor: "Siemens",
    advisorySource: "CISA ICS-CERT",
    published: "2024-01-08T00:00:00Z",
    status: "in_progress",
    exploitAvailable: false,
    patchAvailable: true,
    remediation: "Update firmware to version 17.0.2 or later",
  },
  {
    id: "VLN-003",
    cve: "CVE-2024-0756",
    title: "Weak encryption on Modbus traffic",
    description: "Unencrypted Modbus TCP communication detected on 3 subnets.",
    severity: "high",
    cvss: 7.5,
    affectedAssets: ["AST-003", "AST-007"],
    vendor: "Schneider",
    advisorySource: "Schneider Security",
    published: "2024-01-05T00:00:00Z",
    status: "open",
    exploitAvailable: true,
    patchAvailable: false,
    remediation: "Enforce network segmentation and ACLs",
  },
  {
    id: "VLN-004",
    cve: "CVE-2023-9876",
    title: "Remote code execution in SCADA",
    description: "Critical RCE vulnerability in GE iFIX allowing unauthenticated remote code execution.",
    severity: "critical",
    cvss: 10.0,
    affectedAssets: ["AST-005"],
    vendor: "GE",
    advisorySource: "CISA ICS-CERT",
    published: "2023-12-20T00:00:00Z",
    status: "open",
    exploitAvailable: true,
    patchAvailable: true,
    remediation: "Apply emergency patch GE-2023-12-001",
  },
  {
    id: "VLN-005",
    cve: "CVE-2024-0234",
    title: "Switch configuration exposure",
    description: "SNMP community string exposed allowing configuration read access.",
    severity: "medium",
    cvss: 5.3,
    affectedAssets: ["AST-006"],
    vendor: "Cisco",
    advisorySource: "Cisco Security",
    published: "2024-01-12T00:00:00Z",
    status: "resolved",
    exploitAvailable: false,
    patchAvailable: true,
    remediation: "Change SNMP community strings and enable SNMPv3",
  },
  {
    id: "VLN-006",
    cve: "CVE-2024-0567",
    title: "EtherNet/IP protocol vulnerability",
    description: "Denial of service vulnerability in EtherNet/IP implementation.",
    severity: "medium",
    cvss: 6.5,
    affectedAssets: ["AST-002", "AST-003"],
    vendor: "Rockwell",
    advisorySource: "Rockwell Security",
    published: "2024-01-14T00:00:00Z",
    status: "open",
    exploitAvailable: false,
    patchAvailable: false,
    remediation: "Apply network segmentation and monitor for anomalies",
  },
]

export const remediationTasks = [
  {
    id: "REM-001",
    title: "Patch GE iFIX SCADA Server",
    description: "Apply critical security patch for remote code execution vulnerability",
    priority: "critical",
    status: "in_progress",
    progress: 65,
    assignee: "John Smith",
    dueDate: "2024-01-20T00:00:00Z",
    vulnerabilities: ["VLN-004"],
    assets: ["AST-005"],
    steps: [
      { step: 1, title: "Schedule maintenance window", completed: true },
      { step: 2, title: "Backup current configuration", completed: true },
      { step: 3, title: "Download and verify patch", completed: true },
      { step: 4, title: "Apply patch to test environment", completed: false },
      { step: 5, title: "Validate functionality", completed: false },
      { step: 6, title: "Deploy to production", completed: false },
    ],
  },
  {
    id: "REM-002",
    title: "Update HMI Firmware",
    description: "Upgrade Siemens HMI panels to latest firmware version",
    priority: "high",
    status: "pending",
    progress: 0,
    assignee: "Sarah Johnson",
    dueDate: "2024-01-25T00:00:00Z",
    vulnerabilities: ["VLN-002"],
    assets: ["AST-004"],
    steps: [
      { step: 1, title: "Download firmware package", completed: false },
      { step: 2, title: "Review release notes", completed: false },
      { step: 3, title: "Test on spare unit", completed: false },
      { step: 4, title: "Schedule update window", completed: false },
      { step: 5, title: "Apply firmware update", completed: false },
      { step: 6, title: "Verify operation", completed: false },
    ],
  },
  {
    id: "REM-003",
    title: "Network Segmentation Implementation",
    description: "Implement proper network segmentation for OT/IT boundary",
    priority: "high",
    status: "in_progress",
    progress: 40,
    assignee: "Mike Chen",
    dueDate: "2024-02-01T00:00:00Z",
    vulnerabilities: ["VLN-003", "VLN-006"],
    assets: ["AST-003", "AST-006", "AST-007"],
    steps: [
      { step: 1, title: "Map current network topology", completed: true },
      { step: 2, title: "Design segmentation plan", completed: true },
      { step: 3, title: "Configure firewall rules", completed: false },
      { step: 4, title: "Implement VLANs", completed: false },
      { step: 5, title: "Test connectivity", completed: false },
      { step: 6, title: "Document changes", completed: false },
    ],
  },
  {
    id: "REM-004",
    title: "Credential Rotation",
    description: "Change default credentials on all affected devices",
    priority: "critical",
    status: "completed",
    progress: 100,
    assignee: "Lisa Wong",
    dueDate: "2024-01-15T00:00:00Z",
    vulnerabilities: ["VLN-001"],
    assets: ["AST-001", "AST-002", "AST-004"],
    steps: [
      { step: 1, title: "Inventory default accounts", completed: true },
      { step: 2, title: "Generate new credentials", completed: true },
      { step: 3, title: "Update password vault", completed: true },
      { step: 4, title: "Apply to devices", completed: true },
      { step: 5, title: "Test access", completed: true },
      { step: 6, title: "Update documentation", completed: true },
    ],
  },
]

export const complianceFrameworks = [
  {
    id: "IEC-62443",
    name: "IEC 62443",
    description: "Industrial Automation and Control Systems Security",
    score: 72,
    totalControls: 156,
    passedControls: 112,
    status: "partial",
  },
  {
    id: "NIST-CSF",
    name: "NIST CSF",
    description: "Cybersecurity Framework",
    score: 85,
    totalControls: 108,
    passedControls: 92,
    status: "good",
  },
  {
    id: "ISO-27001",
    name: "ISO 27001",
    description: "Information Security Management",
    score: 68,
    totalControls: 114,
    passedControls: 78,
    status: "partial",
  },
  {
    id: "NERC-CIP",
    name: "NERC CIP",
    description: "Critical Infrastructure Protection",
    score: 91,
    totalControls: 45,
    passedControls: 41,
    status: "good",
  },
]

export const reports = [
  {
    id: "RPT-A7D2",
    name: "OT-Scan-A7D2-Report.pdf",
    type: "Interactive",
    scanId: "#A7D2",
    assets: 82,
    vulnerabilities: 31,
    recommendations: 8,
    severity: "high",
    generated: "2024-01-15T14:30:00Z",
    tags: ["Plant A", "PLC", "Network"],
  },
  {
    id: "RPT-9C12",
    name: "OT-Scan-9C12-Report.pdf",
    type: "PDF",
    scanId: "#9C12",
    assets: 54,
    vulnerabilities: 12,
    recommendations: 5,
    severity: "medium",
    generated: "2024-01-14T10:00:00Z",
    tags: ["Plant B", "HMI"],
  },
  {
    id: "RPT-71B4",
    name: "OT-Scan-71B4-Report.pdf",
    type: "Interactive",
    scanId: "#71B4",
    assets: 120,
    vulnerabilities: 44,
    recommendations: 9,
    severity: "low",
    generated: "2024-01-10T16:45:00Z",
    tags: ["Full Network", "Quarterly"],
  },
]

export const scans = [
  {
    id: "SCN-001",
    name: "Plant A - Nightly",
    status: "completed",
    severity: "critical",
    lastRun: "2024-01-15T10:24:00Z",
    assets: 1482,
    subnets: 12,
    vulnerabilities: 27,
    score: 72,
  },
  {
    id: "SCN-002",
    name: "Plant B - Weekly",
    status: "completed",
    severity: "high",
    lastRun: "2024-01-14T18:02:00Z",
    assets: 856,
    subnets: 8,
    vulnerabilities: 15,
    score: 68,
  },
  {
    id: "SCN-003",
    name: "Lab - On Demand",
    status: "completed",
    severity: "low",
    lastRun: "2024-01-14T11:41:00Z",
    assets: 124,
    subnets: 2,
    vulnerabilities: 3,
    score: 89,
  },
  {
    id: "SCN-004",
    name: "Plant C - Baseline",
    status: "completed",
    severity: "medium",
    lastRun: "2024-01-05T09:00:00Z",
    assets: 672,
    subnets: 6,
    vulnerabilities: 18,
    score: 74,
  },
]

export const trendData = [
  { month: "Aug", vulnerabilities: 45, assets: 320, critical: 8 },
  { month: "Sep", vulnerabilities: 52, assets: 328, critical: 12 },
  { month: "Oct", vulnerabilities: 38, assets: 335, critical: 6 },
  { month: "Nov", vulnerabilities: 41, assets: 340, critical: 9 },
  { month: "Dec", vulnerabilities: 35, assets: 345, critical: 7 },
  { month: "Jan", vulnerabilities: 23, assets: 347, critical: 5 },
]

export const assetDistribution = [
  { name: "PLCs", value: 45, color: "#0ea5e9" },
  { name: "HMIs", value: 28, color: "#22c55e" },
  { name: "SCADA", value: 12, color: "#eab308" },
  { name: "Network", value: 35, color: "#a855f7" },
  { name: "Sensors", value: 127, color: "#f97316" },
  { name: "Drives", value: 100, color: "#ec4899" },
]

export const notifications = [
  {
    id: "NOT-001",
    type: "critical",
    title: "Critical vulnerability detected",
    message: "CVE-2024-1001 affects 3 PLCs in Plant A",
    timestamp: "2024-01-15T10:30:00Z",
    read: false,
  },
  {
    id: "NOT-002",
    type: "warning",
    title: "Scan completed with findings",
    message: "Plant A nightly scan found 27 vulnerabilities",
    timestamp: "2024-01-15T10:24:00Z",
    read: false,
  },
  {
    id: "NOT-003",
    type: "info",
    title: "Firmware update available",
    message: "Siemens released S7-1500 firmware v2.9.5",
    timestamp: "2024-01-15T08:00:00Z",
    read: true,
  },
]
